#!/usr/bin/env python3
"""
Build a Cloudflare D1 seed file from the public directory data.

Reads:  assets/data/restaurant_listings/directory_runtime_data.json
Writes: scripts/seeds/restaurants.sql

Each listing becomes a claimable venue row (status 'unclaimed').
Re-running is safe: statements use INSERT OR IGNORE, so any venue
that already exists in the database is left untouched.

Usage:
  python scripts/build_d1_seed.py
Then apply:
  npx wrangler d1 execute eatouts --file scripts/seeds/restaurants.sql --remote
"""
import json
import os
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "data", "restaurant_listings", "directory_runtime_data.json")
OUT = os.path.join(ROOT, "scripts", "seeds", "restaurants.sql")


def sql_str(value):
    if value is None:
        return "NULL"
    text = str(value)
    if text == "":
        return "NULL"
    return "'" + text.replace("'", "''") + "'"


def main():
    with open(SRC, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    listings = data.get("restaurants", []) if isinstance(data, dict) else data
    now = int(time.time() * 1000)
    lines = [
        "-- Auto-generated by scripts/build_d1_seed.py",
        "-- Source: assets/data/restaurant_listings/directory_runtime_data.json",
        f"-- Listings: {len(listings)}",
        "-- Apply with: npx wrangler d1 execute eatouts --file scripts/seeds/restaurants.sql --remote",
        "",
    ]

    written = 0
    for rec in listings:
        slug = (rec.get("slug") or "").strip()
        name = (rec.get("name") or "").strip()
        if not slug or not name:
            continue
        venue_id = rec.get("id") or ("rest_" + slug)

        cols = [
            "id", "slug", "name", "status", "plan", "claimed",
            "town", "district", "district_name", "area", "landmark",
            "description", "website", "logo_ref", "cover_ref",
            "types", "category", "contacts", "socials",
            "created_at", "updated_at",
        ]
        vals = [
            sql_str(venue_id),
            sql_str(slug),
            sql_str(name),
            sql_str("unclaimed"),
            sql_str("starter"),
            "0",
            sql_str(rec.get("town")),
            sql_str(rec.get("district")),
            sql_str(rec.get("districtName")),
            sql_str(rec.get("area")),
            sql_str(rec.get("landmark")),
            sql_str(rec.get("description")),
            sql_str(rec.get("website")),
            sql_str(rec.get("logo")),
            "NULL",
            # types / contacts / socials stored as JSON text
            sql_str(json.dumps(rec.get("types") or [], ensure_ascii=False)),
            sql_str(rec.get("category")),
            sql_str(json.dumps(rec.get("contacts") or [], ensure_ascii=False)),
            sql_str(json.dumps(rec.get("socials") or [], ensure_ascii=False)),
            str(now),
            str(now),
        ]
        lines.append(
            "INSERT OR IGNORE INTO restaurants (" + ", ".join(cols) + ") VALUES ("
            + ", ".join(vals) + ");"
        )
        written += 1

    lines.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"Wrote {written} venue inserts to {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()